Controllers/BookingController.cs
using AmiFlota.Contracts;
using AmiFlota.Data;
using AmiFlota.Entities;
using AmiFlota.Models;
using AmiFlota.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;


namespace AmiFlota.Controllers
{
    public class BookingController : Controller
    {

        private readonly IBookingService _bookingService;
        private readonly ITripService _tripService;
        private readonly IUserData _userData;
        private int hoursToAutoConfirm = 3;
        private bool autoConfirm = false;
        private bool autoCancellation = false;

        public BookingController(IBookingService bookingService, ITripService tripService, IUserData userData)
        {
            _bookingService = bookingService;
            _tripService = tripService;
            _userData = userData;
        }


        public IActionResult Search()
        {
            return View();
        }

        public async Task<PartialViewResult> FilterCars(string startDate, string endDate)
        {
            AvailableCarsVM carList = await _bookingService.GetAvailableCars(startDate, endDate);

            if (carList.AvailableCars.Count > 0)
            {
                return PartialView("_FilteredCarsView", carList);
            }
            else
            {
                IEnumerable<BookingVM> notConfirmedBookingsList = await _bookingService.GetNotConfirmedBookings(startDate, endDate);
                return PartialView("_NoCarsAvailable", notConfirmedBookingsList);
            }
        }

        public async Task<PartialViewResult> PendingBookingsCurrentUser()
        {
            if (_userData.IsPriviledgedUser())
            {
                var pendingAllBookingsList = await _bookingService.GetAllPendingBookings();
                return PartialView("_PendingBookings", pendingAllBookingsList);
            }
            else
            {
                var pendingBookingsList = await _bookingService.GetPendingBookingsByUserId(_userData.Id);
                return PartialView("_PendingBookings", pendingBookingsList);
            }

        }

        public async Task<PartialViewResult> ApprovedBookingsCurrentUser()
        {
            if (_userData.IsPriviledgedUser())
            {
                var approvedAllBookingsList = await _bookingService.GetAllApprovedBookings();
                return PartialView("_ApprovedBookings", approvedAllBookingsList);
            }
            else
            {
                var approvedBookingsList = await _bookingService.GetApprovedBookingsByUserId(_userData.Id);
                return PartialView("_ApprovedBookings", approvedBookingsList);
            }
        }

        public async Task<PartialViewResult> ActiveBookingsCurrentUser()
        {
            if (_userData.IsPriviledgedUser())
            {
                var activeAllBookingsList = await _bookingService.GetAllActiveBookings();
                return PartialView("_ActiveBookings", activeAllBookingsList);
            }
            else
            {
                var activeBookingsList = await _bookingService.GetActiveBookingsByUserId(_userData.Id);
                return PartialView("_ActiveBookings", activeBookingsList);
            }
        }

        //GET - create
        public PartialViewResult _BookingDetailsModal(string VIN, string startDate, string endDate)
        {
            BookingVM viewModel = new BookingVM()
            {
                UserName = _userData.Name,
                UserId = _userData.Id,
                RegistrationNumber = _bookingService.GetRegistrationNumberByCarVin(VIN),
                StartDate = DateTime.Parse(startDate),
                EndDate = DateTime.Parse(endDate),
            };
            return PartialView("_BookingDetailsModal", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult _BookingDetailsModal(BookingVM viewModel)
        {
            if (ModelState.IsValid)
            {
                _bookingService.BookCar(viewModel);
                return (RedirectToAction("UserDashboard"));
            }
            return View(viewModel);
        }



        public async Task<IActionResult> UserDashboard()
        {
            if(autoConfirm) await _bookingService.AutoConfirmBooking(hoursToAutoConfirm);
            if(autoCancellation) await _bookingService.AutoCancelBooking();
            return View();
        }


        public async Task<IActionResult> Calendar()
        {
            if (autoConfirm) await _bookingService.AutoConfirmBooking(hoursToAutoConfirm);
            if (autoCancellation) await _bookingService.AutoCancelBooking();
            return View();
        }

        public PartialViewResult GetCalendarDataById(int id)
        {
            var booking = _bookingService.GetBookingById(id);
            var trips = _tripService.TripsHistoryByBookingId(id);
            CalendarVM viewModel = new CalendarVM
            {
                Cars = new List<CarModel>(),
                Booking = booking,
                TripsHistory = trips,
            };
        return PartialView("_CalendarEvent", viewModel);
        }

        public async Task<IActionResult> SelectCars()
        {
            await _bookingService.AutoConfirmBooking(3);
            List<CarModel> viewModel = new List<CarModel>();
            viewModel = await _bookingService.GetAllCars();

            return PartialView("_SelectCars", viewModel);
        }

    }
}

Controllers/TripController.cs
using AmiFlota.Contracts;
using AmiFlota.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Security.Claims;
using System.Threading.Tasks;


namespace AmiFlota.Controllers
{
    public class TripController : Controller
    {

        private readonly ITripService _tripService;

        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly string userId;
        private readonly string userName;
        public TripController(ITripService tripService, IHttpContextAccessor httpContextAccessor)
        {
            _tripService = tripService;
            _httpContextAccessor = httpContextAccessor;
            userId = _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            userName = _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.Name);
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public PartialViewResult _TripStartModal(int bookingId) // Boking status not needed?
        {
            TripStartVM viewModel = new TripStartVM()
            {
                BookingId = bookingId,
                /*User = userName*/
            };
            return PartialView("_TripStartModal", viewModel);
        }

        [HttpGet]
        public PartialViewResult _TripEndModal(int bookingId) // Boking status not needed?
        {
            TripEndVM viewModel = _tripService.GetActiveTripByBookingId(bookingId);

            return PartialView("_TripEndModal", viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult StartTrip(TripStartVM viewModel)
        {
            if (ModelState.IsValid)
            {
                _tripService.StartTrip(viewModel);
                return RedirectToAction("UserDashboard", "Booking");
            }
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult FinishTrip(TripEndVM viewModel)
        {
            if (ModelState.IsValid)
            {
                _tripService.FinishTrip(viewModel);
                return RedirectToAction("UserDashboard", "Booking");
            }
            return View(viewModel);
        }

        [AcceptVerbs("GET", "POST")]
        public IActionResult isStartOdoValid(int BookingId, uint StartKm)
        {
            var lastMileage = _tripService.HighestMileageValue(BookingId);

            if (StartKm == lastMileage)
            {
                return Json(true);
            }
            else if (StartKm > lastMileage)
            {
                var difference = StartKm - lastMileage;
                return Json($"Distance of: {difference} km is not saved in database");
            }
            else
            {
                return Json($"Mileage cannot be lower than last saved mileage: {lastMileage} km");
            }

        }

        [AcceptVerbs("GET", "POST")]
        public IActionResult isEndOdoValid(int BookingId, uint EndKm)
        {
            var lastMileage = _tripService.HighestMileageValue(BookingId);

            if (EndKm >= lastMileage)
            {
                return Json(true);
            }
            else
            {
                return Json($"Mileage cannot be lower than last saved mileage: {lastMileage} km");
            }

        }


    }
}

Views/Booking/Calendar.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Calendar</title>
</head>
<body>
    <div id="_CalendarEventModal"> </div>

    <div class="containter-fluid">
        <div class="row row-cols-1 row-cols-sm-1 row-cols-md-1 row-cols-lg-1 row-cols-xl-2">
            <div class="col-12 col-sm-5 col-md-4 col-lg-3 col-xl-3">
                <div id="_selectCars"> </div>
            </div>
            <div class="col-12 col-sm-7 col-md-8 col-lg-9 col-xl-9">
                <div id="calendar"> </div>
            </div>
        </div>
    </div>

    <div id="sizer">
        <div class="d-block d-sm-none d-md-none d-lg-none d-xl-none" data-size="xs"></div>
        <div class="d-none d-sm-block d-md-none d-lg-none d-xl-none" data-size="sm"></div>
        <div class="d-none d-sm-none d-md-block d-lg-none d-xl-none" data-size="md"></div>
        <div class="d-none d-sm-none d-md-none d-lg-block d-xl-none" data-size="lg"></div>
        <div class="d-none d-sm-none d-md-none d-lg-none d-xl-block" data-size="xl"></div>
    </div>



    <div id="loader" data-request-url="@Url.Action("GetCalendarDataById", "Booking")"></div>
</body>

</html>

<script>

    $(document).ready(function() {

        $.ajax({
            url: '@Url.Action("SelectCars", "Booking")',
            datatype: 'html',
            method: 'GET',

            success: function(result) {

                $('#_selectCars').html('').html(result);
                InitializeCalendar();

            },

            error: function(error) {
                console.log(error);
                console.log("Unable to load partial view - Select Cars");
            }
        });
    });

</script>

Views/Booking/Search.cshtml
@*@model AmiFlota.Models.ViewModels.BookingVM*@
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Search for available car</title>
</head>
<body>
    <div id="_BookingDetailsModal"> </div>


    <div class="container-fluid container-lg">
        <div class="row text-center">
            <h2>Booking dates</h2>
        </div>

        <div class="justify-content-center  input-group mb-3">
            <input type="text" class="form-control text-center" placeholder="Booking dates" name="datetimerange" id="datetimeRange" aria-label="Booking dates">
            <button class="btn btn-outline-secondary btn-search" type="button" id="btnSearch">Search</button>
        </div>

        <div id="_SearchingResults"> </div>
    </div>


    <footer>
        @*        <div class="text-right pt-2">
        <p>Confirmation email will be sent to: @HttpContextAccessor.HttpContext.Session.GetString("userEmailAssigned")</p>
        </div>*@
    </footer>

</body>
</html>

<script src="~/js/current-date-time.js"></script>

<script>

    let DateTime = getRoundedSearchDateTime();
    let Limits = getLimitDates();

    //TODO Do not take / return car during the weekends
    $('input[name="datetimerange"]').daterangepicker({
        "showISOWeekNumbers": true,
        "minYear": Limits.YearMin,
        "maxYear": Limits.YearMax,
        "showDropdowns": true,
        "timePicker": true,
        "timePicker24Hour": true,
        "timePickerIncrement": 15,
        "locale": {
            "format": "DD/MM/YYYY HH:mm",
            "separator": " - ",
            "applyLabel": "Apply",
            "cancelLabel": "Cancel",
            "fromLabel": "From",
            "toLabel": "To",
            "customRangeLabel": "Custom",
            "weekLabel": "CW",
            "daysOfWeek": [
                "Su",
                "Mo",
                "Tu",
                "We",
                "Th",
                "Fr",
                "Sa"
            ],
            "monthNames": [
                "January",
                "February",
                "March",
                "April",
                "May",
                "June",
                "July",
                "August",
                "September",
                "October",
                "November",
                "December"
            ],
            "firstDay": 1
        },
        "startDate": DateTime.startDateTime,
        "endDate": DateTime.endDateTime,
        "minDate": Limits.DateMin,
        "maxDate": Limits.DateMax,
        "opens": "center"
    });
</script>

<script>
    $('#btnSearch').on('click', function() {
        var datetimeRangeToParse = document.getElementById('datetimeRange').value;

        const [startDateTime, endDateTime] = datetimeRangeToParse.split(' - ');

        $.ajax({
            url: '@Url.Action("FilterCars", "Booking")',
            datatype: 'html',
            data: { startDate: startDateTime, endDate: endDateTime },
            method: 'GET',

            success: function(result) {
                $('#_SearchingResults').html('').html(result);
            },

            error: function(error) {
                console.log(error);
            }
        });
    });
</script>

Views/Booking/UserDashboard.cshtml
<div id="_TripStartModal"> </div>
<div id="_TripEndModal"> </div>


<div class="container-fluid container-xl no-gutters clearfix">

    <ul class="nav nav-tabs mx-0 px-0" id="dashboardTabs" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="tab-activeBookings" data-bs-toggle="tab" data-bs-target="#active-tab-pane" type="button" role="tab" aria-controls="active-tab-pane" aria-selected="true">Active</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="tab-approvedBookings" data-bs-toggle="tab" data-bs-target="#approved-tab-pane" type="button" role="tab" aria-controls="approved-tab-pane" aria-selected="false">Approved</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="tab-pendingBookings" data-bs-toggle="tab" data-bs-target="#pending-tab-pane" type="button" role="tab" aria-controls="pending-tab-pane" aria-selected="false">Pending</button>
        </li>
    </ul>

    <div class="tab-content mx-0 px-0" id="dashboardTabsContent">
        <div class="tab-pane fade show active" id="active-tab-pane" role="tabpanel" aria-labelledby="active-tab" tabindex="0">
            <div id="_ActiveBookings"> </div>
        </div>
        <div class="tab-pane fade" id="approved-tab-pane" role="tabpanel" aria-labelledby="approved-tab" tabindex="0">
            <div id="_ApprovedBookings"> </div>
        </div>

        <div class="tab-pane fade" id="pending-tab-pane" role="tabpanel" aria-labelledby="pending-tab" tabindex="0">
            <div id="_PendingBookings"> </div>
        </div>
    </div>
</div>


<script>


</script>



<script>
    $(document).ready(function() {


        $.ajax({
            url: '@Url.Action("ActiveBookingsCurrentUser", "Booking")',
            datatype: 'html',
            method: 'GET',

            success: function(result) {
                $('#_ActiveBookings').html('').html(result);
            },

            error: function(error) {
                console.log(error);
                console.log("Unable to load partial view - Active Bookings");
            }
        });

        $.ajax({
            url: '@Url.Action("ApprovedBookingsCurrentUser", "Booking")',
            datatype: 'html',
            method: 'GET',

            success: function(result) {
                $('#_ApprovedBookings').html('').html(result);
            },

            error: function(error) {
                console.log(error);
                console.log("Unable to load partial view - Approved Bookings");
            }
        });


        $.ajax({
            url: '@Url.Action("PendingBookingsCurrentUser", "Booking")',
            datatype: 'html',
            method: 'GET',

            success: function(result) {
                $('#_PendingBookings').html('').html(result);
            },

            error: function(error) {
                console.log(error);
                console.log("Unable to load partial view - Pending Bookings");
            }
        });

    });





</script>

Views/Booking/_ActiveBookingItem.cshtml
@using AmiFlota.Enums
@using AmiFlota.Contracts
@inject IUserData UserData

@model AmiFlota.Models.ViewModels.ActiveBookingVM

@{
    var photoPath = "/images/cars/" + (Model.BookingViewModel.PhotoPath ?? "default.jpg");
}

<div class="card border-0 h-100 mx-0 px-0">
    <div class="row g-0">
        <div class="d-none col-sm-6 d-sm-block col-md-4 d-md-block">
            <img src="@photoPath" class="img-fluid img-heigt-width" alt="Unable to load car photo">
        </div>


        <div class="col-12 col-sm-6 col-md-8">
            <div class="row card-title text-center">
                <h5 class="card-title text-uppercase">@Model.BookingViewModel.RegistrationNumber</h5>

                <div class="card-body">
                    <div class="row">

                        <div class="row row-cols-1 row-cols-sm-1 row-cols-md-1 row-cols-lg-2 mx-0 px-0">
                            <div class="col">
                                <div class="row mx-0 px-0">
                                    <label class="col-5 text-end">Start Date:</label>
                                    <label class="col-7 text-start">@Model.BookingViewModel.StartDate.ToString("dd/MM/yyyy HH:mm") </label>
                                </div>
                                <div class="row mx-0 px-0">
                                    <label class="col-5 text-end">End Date:</label>
                                    <label class="col-7 text-start">@Model.BookingViewModel.EndDate.ToString("dd/MM/yyyy HH:mm") </label>
                                </div>
                            </div>

                            <div class="col">
                                <div class="row mx-0 px-0">
                                    <label class="col-5 text-end">Project:</label>
                                    <label class="col-7 text-start">@Model.BookingViewModel.ProjectCost </label>
                                </div>
                                <div class="row mx-0 px-0">
                                    <label class="col-5 text-end">Description:</label>
                                    <label class="col-7 text-start">@Model.BookingViewModel.Description </label>
                                </div>
                                @if (@UserData.IsPriviledgedUser())
                                {
                                    <div class="row mx-0 px-0">
                                        <label class="col-5 text-end">User:</label>
                                        <label class="col-7 text-start">@Model.BookingViewModel.UserName </label>
                                    </div>
                                }
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

            <div class="row mx-0 px-0 clearfix">
                <div class="accordion px-0 mx-0" id="accordion_@Model.BookingViewModel.Id">
                    <div class="accordion-item">

                        <h2 class="accordion-header" id="accordionHeader_@Model.BookingViewModel.Id">
                            <button class="accordion-button collapsed" type="button"
                                    data-bs-toggle="collapse"
                                    data-bs-target="#accordionBody_@Model.BookingViewModel.Id"
                                    aria-expanded="false"
                                    aria-controls="accordionBody_@Model.BookingViewModel.Id">
                                Trips history
                            </button>
                        </h2>

                        <div id="accordionBody_@Model.BookingViewModel.Id" class="accordion-collapse collapse">

                            <div class="accordion-body">
                                <div class="row">
                                    <partial name="_TripsHistory" model=@Model.TripsHistory class="mx-0 px-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

Views/Booking/_ActiveBookings.cshtml
@using AmiFlota.Enums
@using AmiFlota.Contracts
@inject IUserData UserData
@model IEnumerable<AmiFlota.Models.ViewModels.ActiveBookingVM>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Bookings list</title>
</head>
<body>
    @if (Model.Count() > 0)
    {

        @foreach (var booking in Model)
        {

            <div class="row mt-4 border border-dark border-opacity-25">
                <partial name="_ActiveBookingItem" model=booking />
            </div>

            <div class="row border-0 text-end">
                <div class="col-12 border-0 mx-0 px-0" role="group">

                   @if (@UserData.IsPriviledgedUser(booking.BookingViewModel.UserName))

                    {
                        @if (booking.BookingViewModel.BookingStatus.Equals(BookingStatus.Active))
                        {
                            <button type="button" id="btnDashboardStartTrip"
                    class="btn btn-success mx-0 px-4 btn-active-start-trip"
                    data-id="@booking.BookingViewModel.Id"
                    data-url="@Url.Action("_TripStartModal", "Trip")">
                                Start trip
                            </button>

                            <button type="button" id="btnDashboardReturnCar"
                    class="btn btn-dark mx-0 px-4 btn-active-return-car"
                    data-id="@booking.BookingViewModel.Id">
                                Return the car
                            </button>
                        }

                        @if (booking.BookingViewModel.BookingStatus.Equals(BookingStatus.OnTheWay))
                        {
                            <button type="button" id="btnDashboardEndTrip"
                    class="btn btn-success mx-0 px-4 btn-active-end-trip"
                    data-id="@booking.BookingViewModel.Id"
                    data-url="@Url.Action("_TripEndModal", "Trip")">
                                End trip
                            </button>
                        }
                    }

                </div>
            </div>
        }

    }
    else
    {
        <h2>No active bookings found</h2>
    }
</body>
</html>

<script>
    $(document).ready(function() {
        $(".btn-active-return-car").click(function() {
            var BookingId = $(this).data("id");


            $.ajax({
                url: routeURL + '/api/Booking/ReturnCar',
                type: 'GET',
                data: { bookingId: BookingId },
                dataType: 'JSON',
                success: function(response) {
                    if (response.status === 1) {
                        location.reload();
                        $.notify(response.message, "success");
                    }
                    else {
                        $.notify(response.message, "error");
                    }

                },
                error: function(xhr) {
                    $.notify("Error", "error");
                }
            });
        });

        $(".btn-active-start-trip").click(function() {
            var BookingId = $(this).data("id");
            var UrlRequest = $(this).data('url');

            $.validator.unobtrusive.parse("#tripStartModal");

            $.ajax({
                url: UrlRequest,
                datatype: 'html',
                data: { bookingId: BookingId },
                method: 'GET',

                success: function(result) {
                    $('#_TripStartModal').html('').html(result);
                    onShowTripStartModal();


                        bindForm(this);
                },

                error: function(xhr, status, error) {
                    console.log("error");
                }
            });
        });

            function bindForm(dialog) {
                $("#tripStartModal", dialog).submit(function() {
                    
                    if (this.valid()) {
                        $.ajax({
                            url: this.action,
                            type: this.method,
                            data: $(this).serialize(),
                            success: function(result) {
                                if (result.success) {
                                    $('#tripStartModal').modal('hide');
                                    location.reload();
                                } else {
                                    $('#tripStartModal').html(result);
                                    bindForm();
                                }
                            }
                        });
                        return false;
                    }
                });
            }


        function onShowTripStartModal() {
            $("#tripStartModal").modal("show");
        }


        $(".btn-active-end-trip").click(function() {
            var BookingId = $(this).data("id");
            var UrlRequest = $(this).data('url');

            $.ajax({
                url: UrlRequest,
                datatype: 'html',
                data: { bookingId: BookingId },
                method: 'GET',

                success: function(result) {
                    $('#_TripEndModal').html('').html(result);
                    onShowTripEndModal();
                },

                error: function(xhr, status, error) {
                    console.log("error");
                }
            });
        });

        function onShowTripEndModal() {
            $("#tripEndModal").modal("show");
        }
    });
</script>

Views/Booking/_ApprovedBookings.cshtml
@using AmiFlota.Enums
@using AmiFlota.Contracts
@inject IUserData UserData

@model IEnumerable<AmiFlota.Models.ViewModels.BookingVM>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Bookings list</title>
</head>
<body>

    @if (Model.Count() > 0)
    {
        <h2>Approved bookings</h2>
        @foreach (var booking in Model)
        {
            <div class="row mt-4 border border-dark border-opacity-25">
                <partial name="_BookingListItem" model=booking />
            </div>

            <div class="row border-0 text-end">
                <div class="col-12 border-0 mx-0 px-0" role="group">

                   @if (@UserData.IsPriviledgedUser(booking.UserName))
                    {
                        @if (DateTime.Now >= booking.StartDate && DateTime.Now <= booking.EndDate)
                        {
                            <button type="button" id="btnDashboardTakeCar" class="btn btn-dark mx-0 px-4 btn-approved-take-car" data-id="@booking.Id">Take the car</button>
                        }

                        <button type="button" id="btnDashboardReject" class="btn btn-warning mx-0 px-4 btn-approved-reject" data-id="@booking.Id">Reject</button>
                        <button type="button" id="btnDashboardDelete" class="btn btn-danger mx-0 px-4 btn-approved-delete" data-id="@booking.Id">Delete</button>
                    }
                </div>
            </div>
        }
    }
    else
    {
        <h2>No approved bookings found</h2>
    }
</body>
</html>

<script src="~/js/current-date-time.js"></script>

<script>
    $(document).ready(function() {

        $(".btn-approved-take-car").click(function() {
            var BookingId = $(this).data("id");
            
            $.ajax({
                url: routeURL + '/api/Booking/TakeCar',
                type: 'GET',
                data: { bookingId: BookingId },
                dataType: 'JSON',
                success: function(response) {
                    if (response.status === 1) {
                        location.reload();
                        $.notify(response.message, "success");
                    }
                    else {
                        $.notify(response.message, "error");
                    }

                },
                error: function(xhr) {
                    $.notify("Error", "error");
                }
            });
        });

        $(".btn-approved-reject").click(function() {
            var BookingId = $(this).data("id");

            $.ajax({
                url: routeURL + '/api/Booking/RejectEvent',
                type: 'GET',
                data: { id: BookingId },
                dataType: 'JSON',
                success: function(response) {
                    if (response.status === 1) {
                        location.reload();
                    }
                    else {
                        $.notify(response.message, "error");
                    }

                },
                error: function(xhr) {
                    $.notify("Error", "error");
                }
            });
        });

        $(".btn-approved-delete").click(function() {
            var BookingId = $(this).data("id");

            $.ajax({
                url: routeURL + '/api/Booking/DeleteEvent',
                type: 'GET',
                data: { id: BookingId },
                dataType: 'JSON',
                success: function(response) {
                    if (response.status === 1) {
                        location.reload();
                    }
                    else {
                        $.notify(response.message, "error");
                    }

                },
                error: function(xhr) {
                    $.notify("Error", "error");
                }
            });
        });
    });
</script>

Views/Booking/_SelectCars.cshtml
@using AmiFlota.Enums
@model List<AmiFlota.Models.CarModel>

@{
    TrunkType tempValue = new TrunkType();

    @foreach (var car in Model)
    {
        if (!car.Trunk.Equals(tempValue))
        {

            <h5 class="cente">@car.Trunk</h5>
            tempValue = @car.Trunk;
        }

        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="@car.VIN" id="@car.VIN" checked="checked" />
            <label class="form-check-label">@car.Brand @car.Model @car.RegistrationNumber</label>
        </div>
    }
}


<script src="~/js/script-custom-calendar.js"></script>